project:
  type: website

website:
  title: "Beyond the Classroom"
  navbar:
    background: "#FFF7E6"
    foreground: "black"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: narrative.qmd
        text: Narrative 
      - href: data_critique.qmd
        text: Data Critique
      - href: case_study.qmd
        text: Case Study
      - href: viz.qmd
        text: Visualizations
      - href: annotated_bib.qmd
        text: Annotated Bibliography
        

format:
  html:
    title-block: true
    title-block-banner: true
    page-layout: full
    theme:
      - minty
      - brand
    css: styles.css
    toc: true


