project:
  type: website

website:
  title: "Beyond the<br>Classroom"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_critique.qmd
        text: Data Critique
      - href: rq1.qmd
        text: Research Q 1
      - href: rq2.qmd
        text: Research Q 2
      - href: rq3.qmd
        text: Research Q 3
      - href: viz.qmd
        text: Visualizations
      - href: sources.qmd
        text: Sources
      - href: annotated_bib.qmd
        text: Annotated Bibliography
        

format:
  html:
    title-block: true
    title-block-banner: true
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

