---
title: "Annotated <br>Bibliography"
title-block-banner: "banner.jpeg"
page-layout: full
---

# Citations

::: hanging-indent
Addo, F. R., Sassler, S., & Williams, K. (2016). Reexamining the Association of Maternal Age and Marital Status at First Birth With Youth Educational Attainment. Journal of Marriage and Family, 78(5), 1252–1268. https://doi.org/10.1111/jomf.12360
:::

Addo, Sassler, and Williams (2016) use data from the Children and Young Adult sample of the 1979 National Longitudinal Survey of Youth to examine how maternal age and marital status at birth influence children’s chances of completing high school. The study finds that children of older teen mothers are no more likely to graduate than those of younger teen mothers. However, children born to young adult mothers (ages 20–24) have higher odds of finishing high school than those born to teen mothers, though they remain at a disadvantage compared to children whose mothers were 25 or older at birth. The authors also find that being born to an unmarried mother lowers the likelihood of high school completion, regardless of race or ethnicity. Overall, this study highlights the persistent educational disadvantages linked to early and nonmarital childbearing and underscores the importance of maternal age and family structure in shaping children’s educational outcomes.

::: hanging-indent
Akanbi, Moses A., et al. “Influence of Socio-Economic Factors on Prevalence of Teenage Pregnancy in Nigeria.” African Journal of Reproductive Health, vol. 25, no. 5s, 2021, pp. 138–46, https://doi.org/10.29063/ajrh2021/v25i5s.13.
:::

Akanbi argues that religious affiliation, socio-economic status, child marriage, and education level play a large role in early pregnancy rates in Nigeria citing hard evidence of these phenomena. The evidence that is presented is from a study regarding teenage pregnancy in Nigeria for women before the age of 20 years old. The correlations are clear that approximately a fifth of girls in ages 15-19 experienced teenage pregnancy in Nigeria. Akanbi also notes how girls from more rural areas and girls in Muslim families experience more teenage pregnancy. This resource is important as it cites critical statistics on how early pregnancy is induced by factors like location, religion, region, education, marital status, and family planning facilities. This resource specifically helps us target our thesis by affirming how lower educational levels leads to less knowledge on reproductive health care and therefore risks of pregnancy. It also reaffirms some of our side theses on economic status and religious influences on birth rates.

::: hanging-indent
Azzopardi, Peter S., et al. “Progress in Adolescent Health and Wellbeing: Tracking 12 Headline Indicators for 195 Countries and Territories, 1990–2016.” The Lancet (British Edition), vol. 393, no. 10176, 2019, pp. 1101–18 https://doi.org/10.1016/S0140-6736(18)32427-9.
:::

Azzopardi argues that while adolescent health has improved in some respects from 1990-2016, immense and substantial inequalities persist globally. The authors use data from 195 countries, measuring twelve key health indicators like fertility rates, education levels, nutrition, substance use, etc. This source is important because it provides a large-scale, data-driven overview of how adolescent health differs across regions and genders. It connects to the overall vision for our paper by showing that gender inequality, such as higher rates of child marriage, limited education, and poor reproductive health access, continues to negatively affect female health in developing countries. The authors show that diseases linked to poverty, like infections and malnutrition, have gone down, but because of population growth in poorer countries, more teens are still living in tough health conditions. Overall, the study says that schools, health systems, and laws have not kept up with the changes teens are facing, and that gender inequality continues to be a major reason why females in developing countries often have worse health outcomes than males.

::: hanging-indent
Hagues, R. J., Bae, D., & Wickrama, K. K. A. S. (2017). Mediational Pathways Connecting Secondary Education and Age at Marriage to Maternal Mortality: A Comparison between Developing and Developed Countries. Women & Health, 57(2), 189–207. https://doi.org/10.1080/03630242.2016.1159266
:::

Hagues, Bae, Wickrama argue that secondary education and the age at which women marry are crucial in reducing maternal mortality, but that these factors operate through ‘mediational pathways,’ or indirectly. Greater attainment of education and a later marriage age are associated with reduced maternal mortality. The study uses data from the national statistical databases of both developed and developing countries. This study is crucial in that it unlocks how education and marrying at a later age for women can prevent high rates of maternal mortality - leading to policy implications that could prevent unnecessary death during childbirth and beyond. The findings of this study provide evidence that through education, maternal mortality is somewhat avoidable. Because education attainment and marriage age is very gender-biased in both developing and developed countries, it is crucial to explore the imbalance between these factors.

::: hanging-indent
Leybourne, G. G., & White, K. (1940). Education and the birth-rate, a social dilemma / by Grace G. Leybourne and Kenneth White, with a foreword by A.M. Carr Saunders, and an introd. by R.H. Tawney. J. Cape.
:::

In this book, Leybourne and White explore the relationship between educational attainment, social class, and declining birth rates in early 20th-century Britain. The authors argue that rising educational opportunities, especially for women, contributed to changes in family planning, delayed marriage, and smaller family sizes, posing what they describe as a “social dilemma” for national population growth. The book displays demographic patterns within broader debates about social progress, gender roles, and economic stability. Although dated in its empirical methods and social assumptions, the book remains significant as an early attempt to link education and fertility within a sociological framework and provides valuable historical insight into early twentieth-century population issues.

::: hanging-indent
McGillivray, Mark, et al., editors. Health Inequality and Development. Palgrave Macmillan UK, 2011. DOI.org (Crossref), https://doi.org/10.1057/9780230304673.
:::

In this book, McGillivary argues that inequalities in developing countries, in particular, are intertwined with social, policy, and economic factors that can be found in health outcomes that demonstrate patterns of gendered disadvantage and exclusion in education. In terms of resources, it utilizes a variety of empirical chapters that feature micro and macro level data analysis. These analyses include case studies regarding child nutrition and female labor market participation. This resource links health inequalities to big societal issues such as lack of job opportunities and education. This source helps explain that in order to solve some of these issues, more action than simple medical care will need to be implemented. This book relates women’s education to societal inequality and reproductive and healthcare injustice.

::: hanging-indent
Okonofua, Friday. « Economic Development and Reproductive Health in Africa / Développement économique et santé reproductive en Afrique ». African journal of reproductive health, vol. 1, no 2, 1997, p. 6‑9. https://search.library.ucla.edu/permalink/01UCS_LAL/192ecse/cdi_unpaywall_primary_10_2307_3583371
:::

Okonofua presents in their piece that reproductive health in sub-Saharan African countries is generally inferior to other nations including the higher rate of sexually transmitted diseases, maternal mortality, infertility, and access to safe reproductive health services. Okonofua argues that this is due to the substandard socio-economic status and education levels of women in sub-Saharan Africa. The resource the author uses largely comes from the World Health Organization. This resource is so important because it highlights how poverty is one of the key contributing factors to reproductive health in these regions contributing to a lack of knowledge through education and lack of resources. This resource supports our thesis as this research is even showing that these conditions may even be worsening in several regions, with maternal mortality rates increasing in Nigeria.

::: hanging-indent
Okui, T. (2023). Analysis of an Association between Preterm Birth and Parental Educational Level in Japan Using National Data. Children, 10(2), 342-. https://doi.org/10.3390/children10020342
:::

Through this study, Okui displays how lower parental education level is linked to a higher rate of preterm birth risk. This study was conducted using data from national linked data sets of Japan, including census data and statistics from the national department of education. The findings in this study are important because they emphasize that a higher level of education can help to prevent the health risks of preterm births, both to the infant and to the parent. It provides empirical evidence that a higher level of education in both parents leads to safer births, potentially leading to the understanding that gender imbalance in education can lead to medical issues, especially in pregnant women.

::: hanging-indent
Pezzulo, Carla, et al. “Geographical Distribution of Fertility Rates in 70 Low-Income, Lower-Middle-Income, and Upper-Middle-Income Countries, 2010–16: A Subnational Analysis of Cross-Sectional Surveys.” The Lancet Global Health, vol. 9, no. 6, 2021, pp. e802–12, https://doi.org/10.1016/S2214-109X(21)00082-6.
:::

Pezzulo argues through their research that in more rural and lower income areas, there are often high-fertility clusters. The research also demonstrates how rates of women with secondary education are higher in low-feritility clusters and areas with low contraceptive use are correlated with high-fertility clusters. This research is coming from clustering analysis of cross-sectional surveys across 70 countries in Africa, Asia, and Latin America and the data was from demographic and health surveys, UNICEF, and multiple indicator cluster Surveys. This resource is critical as it identifies areas of low-fertility clusters and associated variable correlations in those regions, helping us pinpoint the factors influencing fertility rates in specific regions. In terms of our thesis, this specifically supports our hypothesis that region specific factors influence fertility rate and targeting variables like education level and access to reproductive resources lower fertility rates and can be targeted to specific high-fertility cluster regions.

::: hanging-indent
Ran, Na. “Study of Impacts of Education, Open-Access Medical Publishing, and Internet on Women’s Health in China.” Health Care for Women International, vol. 44, no. 9, 2023, pp. 1273–89, https://doi.org/10.1080/07399332.2022.2096888.
:::

Na Ran articulates that higher female education, greater internet access, and mobile phone usage, and wider availability of open-access medical research are all significantly associated with lower mortality rates among women and girls in China. The author utilizes quantitative analyses of national data on women’s mortality alongside indicators such as female school enrollment, mobile subscriptions, internet access, and counts of open-access medical articles, revealing strong negative correlations. This source is important because it shows how knowledge and information-based tools such as education, digital access, and scholarly publishing play a role in improving women’s health outcomes beyond just medical interventions. Regarding our topic on gendered health in developing countries, it provides evidence that access to education and digital/information resources can reduce gendered health disparities by empowering women with knowledge and connectivity that will complement and deepen our focus on gendered social determinants of health.

::: hanging-indent
Rizvi, Javed H., and Nadeem F. Zuberi. “Women’s Health in Developing Countries.” Best Practice & Research Clinical Obstetrics & Gynaecology, vol. 20, no. 6, Dec. 2006, pp. 907–22. DOI.org (Crossref), https://doi.org/10.1016/j.bpobgyn.2006.06.005.
:::

Rizvi and Zuberi (2006) argue that women in developing countries face a large obstacle with gynaecological and reproductive health and that any improvement that is intended to be made in the field of women’s health requires community involvement, a variety of reforms, and proper resource allocation. The resource utilizes pre-existing synthesized sources from the Reproductive Health Library and the Cochrane Library. Additionally, some data and information can be categorized as clinical and regional epidemiological data. These resources were compiled to create a variety of data about the epidemiology of abortion, sexual health issues, and many other gynaecological problems experienced by women in developing countries. The importance of this resource lies in the open view it brings to women’s health in low-resource environments. It highlights the gaps in policy and knowledge that are present in some developing countries. This article provides context in relation to female education and reproductive health issues in developing countries by demonstrating how inadequate health services and gaps in policy weaken female reproductive health. This in turn affects educational and economic opportunities.

::: hanging-indent
Saliba, Matilda, and Huda Zurayk. “Expanding Concern for Women’s Health in Developing Countries.” Women’s Health Issues, vol. 20, no. 3, May 2010, pp. 171–77. DOI.org (Crossref), https://doi.org/10.1016/j.whi.2010.01.001.
:::

Saliba and Zurayk argue that women’s health in developing countries, particularly in the Eastern Mediterranean Region (EMR), should be expanded beyond the constraints of reproductive health and reproductive ages, in order to include long-term conditions and health at different stages of age. They use epidemiological and public health data that details the implications and burdens of major non-communicable diseases among women in the Eastern Mediterranean Region. This journal article expands the scope of “women’s health” in developing countries. It highlights that focusing on only reproduction significantly misrepresents significant diseases and other non-maternal burdens. Although my thesis gears toward female education, fertility, and access to healthcare, this resource helps by broadening the scope. It highlights that women’s health outcomes, thus the value of their education and health access, extends beyond the regulated scope of fertility. It supports the argument that improving women’s education and healthcare access has implications not just for reproductive health, but for overall lifelong health.

::: hanging-indent
Singh, Harpreet, and Rana Amanat Singh. “Gender and Inequality in Access to Healthcare Facilities in India: Evidence from NSSO’s 75th Round on Health.” Millennial Asia, 2023, https://doi.org/10.1177/09763996231195663.
:::

In this article, Harpreet Singh and Rana Amanat Singh analyze gender inequalities in access to healthcare in India applying data from the National Sample Survey Office’s 75th Round on Health (2017–2018). The authors collaborated to have a Gender Parity Index (GPI) to measure the difference of both men and women’s difference in getting access to healthcare support. The research found that on an average, women are more likely to be facing barriers getting medical aid. Especially for women living in rural areas who are facing a double burden where there was a lack of resources and more relied on public or underdeveloped service. In comparison, males are more likely to get healthcare benefits and high-quality service such as private hospitals. The research argues that there’s a structural gender inequality, economical struggles and also a control under the patriarchal norms. The article concluded that there should be a policy constructed that focused on both accessibility and that are sensitive to gender norms. The article can be seen as valuable evidence that there’s a coexisting relationship between gender inequality, geographical locations and socioeconomic positions that are together impacting the national healthcare system of India.

::: hanging-indent
Stange, K. (2011). A Longitudinal Analysis of the Relationship Between Fertility Timing and Schooling. Demography, 48(3), 931–956. https://doi.org/10.1007/s13524-011-0050-3
:::

Stange (2011) conducts a longitudinal study examining how the timing of fertility influences women’s postsecondary educational attainment, with particular attention to dynamic selection processes. These processes capture how women’s educational and fertility decisions evolve together over time, reflecting not only fixed characteristics such as background or ability but also time-varying factors that lead some women to diverge from educational paths even before pregnancy occurs. Using a matching approach based on predicted birth hazard rates, Stange compares eventual mothers with non-mothers who share similar pre-pregnancy characteristics. The study finds that both groups initially enter college at similar rates, but their educational trajectories begin to differ before childbirth, suggesting that pre-pregnancy factors drive much of the observed educational gap. Stange concludes that conventional controls and fixed-effects models fail to account for this dynamic selection bias, highlighting the need for models that jointly consider fertility and educational decision-making. This research provides a nuanced understanding of how the timing and sequencing of life events shape women’s educational outcomes.

::: hanging-indent
Tamir, Tadesse Tarik. “Neonatal Mortality Rate and Determinants among Births of Mothers at Extreme Ages of Reproductive Life in Low and Middle Income Countries.” Scientific Reports, vol. 14, no. 1, 12596, 2024, https://doi.org/10.1038/s41598-024-61867-w.
:::

This article argues that neonates born to mothers at the extreme ends of reproductive age, adolescents, and older mothers in low and middle-income countries face higher mortality risks compared to those born to mothers in the typical reproductive age range. The authors use secondary analysis of demographic and health survey data from 43 low and middle-income countries, including a total sample of 151,685 live births, and employ a multilevel mixed-effects model to identify specific determinants of neonatal mortality such as maternal education, home delivery, multiple births, country-level fertility, etc. This source is important because it highlights how maternal age as a social and biological factor intersects with other vulnerabilities, such as low education or home birth, to affect newborn survival in developing settings. This will support our project on gendered health in developing countries as it shows how maternal age, which often correlates with gendered norms such as early childbearing or older motherhood, can contribute to gender specific risks for newborns, thereby reinforcing the argument that gendered social factors shape health outcomes in low-income contexts.

::: hanging-indent
World Health Organization. “Maternal Health.” WHO, 23 Sept. 2019, www.who.int/news-room/fact-sheets/detail/maternal-health.
:::

::: hanging-indent
Yan, J., Wang, L., Yang, Y., Zhang, Y., Zhang, H., He, Y., Peng, Z., Wang, Y., Wang, Q., Shen, H., Zhang, Y., Yan, D., Ma, X., & Yang, H. (2020). The trend of caesarean birth rate changes in China after ‘universal two-child policy’ era: a population-based study in 2013–2018. BMC Medicine, 18(1), Article 249. https://doi.org/10.1186/s12916-020-01714-7
:::

This study indicates that in China, the implementation of the two-child policy first led to a decline in caesarean birth rates, and then increased between two and three years after the policy was introduced. This study is based off of a population-based data set from the National Free Pre-Pregnancy Check-Ups Project, which included data from 31 provinces of mainland China from 2013-2018. Through this study, we can understand more about how large-scale policy changes can influence obstetric outcomes and demographic outcomes. This study highlights the gender-imbalanced variable of maternal health with respect to access and risk in health system practices. Because the C-section rate has implications for maternal and newborn health, it is crucial to investigate how these policy changes can affect men and women alike.

::: hanging-indent
Zeng, Junxia, et al. “Gender Inequality in Education in China: A Meta-Regression Analysis.” Contemporary Economic Policy, vol. 32, no. 2, 2014, pp. 474–91, https://doi.org/10.1111/coep.12006.
:::

Junxia Zeng and her team assessed the level of gender inequality in education and its trend in the late 20th century of China, by using metadata analysis. By examining many studies and researches, the author quantified the gender factors influencing educational success and outcomes. That there’s a difference in education outcomes and success rates in different areas, levels and times in China. The data have shown that although the level of education disparity is getting less, it still exists especially in rural areas and families with low incomes. The research pointed out that the gender inequality of China is largely due to poor socioeconomic positions, lack of implementation of policies and that Chinese society has a favor of sacrificing women’s education rights to their male relatives first. The conclusion stated that there should be an ongoing focus on ensuring the rights of education for women, especially in rural areas and underdeveloped provinces. This article provided a powerful example to how economic and education policies reforms can better shape gender equality in China.
